version: '3.8'
services:
    nginx:        
        image: sciohub/innovation-catalogue-connect-nginx:staging
        container_name: laravel-nginx
        restart: unless-stopped
        volumes:
          - /etc/letsencrypt/live/staging.innovation.api.scio.services/fullchain.pem:/etc/letsencrypt/live/staging.innovation.api.scio.services/fullchain.pem
          - /etc/letsencrypt/live/staging.innovation.api.scio.services/privkey.pem:/etc/letsencrypt/live/staging.innovation.api.scio.services/privkey.pem
        ports:
          - 50100:443
          - 50101:80

    php:
        image: sciohub/innovation-catalogue-connect:staging
        container_name: laravel-app
        restart: unless-stopped